apiVersion: v1
data:
  init.sql: |-
    CREATE TABLE IF NOT EXISTS accounts (
        id CHAR(27) PRIMARY KEY,
        name VARCHAR(24) NOT NULL
    );
kind: ConfigMap
metadata:
  name: account-db-init
